# Generated by Django 5.1.6 on 2025-02-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("img", models.ImageField(upload_to="images/")),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(verbose_name=500)),
            ],
        ),
    ]
