# Generated by Django 5.1.6 on 2025-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_place_created_at_place_rating_place_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
