# Generated by Django 5.1.6 on 2025-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_category_delete_user_alter_place_img_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="category",
        ),
        migrations.AddField(
            model_name="place",
            name="category",
            field=models.ManyToManyField(to="places.category"),
        ),
    ]
