# Generated by Django 5.1.6 on 2025-03-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_remove_place_category_place_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
